name: Next release

on:
  push:
    branches: [ master ]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: PWD
        run: ls | echo $1

      - name: Publish to NPM
        run: cd ./vuepress-plugin && npm publish || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
