name: NPM Package

on:
  push:
    branches: [ master ]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}